# Generated by Django 5.2.1 on 2025-06-01 02:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('sequence', models.TextField()),
                ('chromosome', models.CharField(blank=True, max_length=30, null=True)),
                ('start', models.BigIntegerField(blank=True, null=True)),
                ('end', models.BigIntegerField(blank=True, null=True)),
                ('strand', models.CharField(blank=True, max_length=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Genes',
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('scientific_name', models.CharField(blank=True, max_length=150)),
                ('common_name', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Species',
            },
        ),
        migrations.CreateModel(
            name='CrisprEdit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_sequence', models.CharField(max_length=100)),
                ('replacement_sequence', models.CharField(max_length=100)),
                ('edited_sequence', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='crispr.gene')),
            ],
            options={
                'verbose_name_plural': 'Editions',
            },
        ),
        migrations.AddField(
            model_name='gene',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genes', to='crispr.species'),
        ),
    ]
