# Generated by Django 5.2.1 on 2025-06-01 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crispr', '0002_remove_gene_chromosome_remove_gene_end_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crispredit',
            options={'verbose_name_plural': 'CRISPR Edits'},
        ),
        migrations.AddField(
            model_name='gene',
            name='sequence',
            field=models.TextField(blank=True, help_text='Full gene sequence', null=True),
        ),
        migrations.AlterField(
            model_name='gene',
            name='bin',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Indexing field for fast queries', null=True),
        ),
        migrations.AlterField(
            model_name='gene',
            name='cdsEnd',
            field=models.PositiveIntegerField(blank=True, help_text='CDS end', null=True),
        ),
        migrations.AlterField(
            model_name='gene',
            name='cdsStart',
            field=models.PositiveIntegerField(blank=True, help_text='CDS start', null=True),
        ),
        migrations.AlterField(
            model_name='gene',
            name='chrom',
            field=models.CharField(blank=True, help_text='Chromosome or scaffold', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gene',
            name='exonEnds',
            field=models.TextField(blank=True, help_text='Comma-separated exon ends', null=True),
        ),
        migrations.AlterField(
            model_name='gene',
            name='exonFrames',
            field=models.TextField(blank=True, help_text='Exon reading frames', null=True),
        ),
        migrations.AlterField(
            model_name='gene',
            name='exonStarts',
            field=models.TextField(blank=True, help_text='Comma-separated exon starts', null=True),
        ),
        migrations.AlterField(
            model_name='gene',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gene',
            name='strand',
            field=models.CharField(blank=True, choices=[('+', '+'), ('-', '-')], help_text='Strand direction', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='gene',
            name='txEnd',
            field=models.PositiveIntegerField(blank=True, help_text='Transcription end', null=True),
        ),
        migrations.AlterField(
            model_name='gene',
            name='txStart',
            field=models.PositiveIntegerField(blank=True, help_text='Transcription start', null=True),
        ),
    ]
