name: geaxis

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10.12]

    steps:
      - name: code checkout
        uses: actions/checkout@v4

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: libs
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-cov django djangorestframework requests pillow drf_yasg python-dotenv pandas
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: recent commits
        run: git log --oneline -n 10

      - name: changelog
        uses: TriPSs/conventional-changelog-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-version-file: false
          skip-commit: false
          output-file: CHANGELOG.md
          skip-tag: false
